# Fichero de Secretos para la App de Rutas

# Credenciales para el login
[credentials]
usernames = ["antonio", "albert", "paqui"]
password = "elnota"

# Claves de Supabase (las usaremos en el siguiente paso)
[supabase]
url = "https://btvpgijojfzfsxbbfnwi.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0dnBnaWpvamZ6ZnN4YmJmbndpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMTE3NzIsImV4cCI6MjA3NDU4Nzc3Mn0.IVMl48V2CaQgKgHwQ6x7VEzObu_ptFK4Dta2cRMOPH0"